#!/bin/sh
systemctl enable NetworkManager.service
systemctl enable auto-cpufreq.service
systemctl enable firewalld.service
systemctl enable libvirtd.service
systemctl enable thermald.service
systemctl enable fstrim.timer
systemctl enable pkgfile-update.timer
systemctl enable apparmor.service
systemctl enable reflector.timer